// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: transaction-service/pb/Transactions.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreditAccountRequestBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Amount int32  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *CreditAccountRequestBody) Reset() {
	*x = CreditAccountRequestBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_pb_Transactions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditAccountRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountRequestBody) ProtoMessage() {}

func (x *CreditAccountRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_pb_Transactions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountRequestBody.ProtoReflect.Descriptor instead.
func (*CreditAccountRequestBody) Descriptor() ([]byte, []int) {
	return file_transaction_service_pb_Transactions_proto_rawDescGZIP(), []int{0}
}

func (x *CreditAccountRequestBody) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreditAccountRequestBody) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreditAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body *CreditAccountRequestBody `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *CreditAccountRequest) Reset() {
	*x = CreditAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_pb_Transactions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountRequest) ProtoMessage() {}

func (x *CreditAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_pb_Transactions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountRequest.ProtoReflect.Descriptor instead.
func (*CreditAccountRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_pb_Transactions_proto_rawDescGZIP(), []int{1}
}

func (x *CreditAccountRequest) GetBody() *CreditAccountRequestBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type DebitAccountRequestBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Amount int32  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *DebitAccountRequestBody) Reset() {
	*x = DebitAccountRequestBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_pb_Transactions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebitAccountRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitAccountRequestBody) ProtoMessage() {}

func (x *DebitAccountRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_pb_Transactions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitAccountRequestBody.ProtoReflect.Descriptor instead.
func (*DebitAccountRequestBody) Descriptor() ([]byte, []int) {
	return file_transaction_service_pb_Transactions_proto_rawDescGZIP(), []int{2}
}

func (x *DebitAccountRequestBody) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DebitAccountRequestBody) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DebitAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body *DebitAccountRequestBody `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *DebitAccountRequest) Reset() {
	*x = DebitAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_pb_Transactions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebitAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitAccountRequest) ProtoMessage() {}

func (x *DebitAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_pb_Transactions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitAccountRequest.ProtoReflect.Descriptor instead.
func (*DebitAccountRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_pb_Transactions_proto_rawDescGZIP(), []int{3}
}

func (x *DebitAccountRequest) GetBody() *DebitAccountRequestBody {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_transaction_service_pb_Transactions_proto protoreflect.FileDescriptor

var file_transaction_service_pb_Transactions_proto_rawDesc = []byte{
	0x0a, 0x29, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x51, 0x0a,
	0x14, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x22, 0x47, 0x0a, 0x17, 0x44, 0x65, 0x62, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4f, 0x0a, 0x13, 0x44, 0x65, 0x62,
	0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x38, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x62,
	0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0xef, 0x01, 0x0a, 0x15, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x50, 0x43, 0x12, 0x6a, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x22, 0x10, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x75, 0x70, 0x3a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x12, 0x6a, 0x0a, 0x0c, 0x44, 0x65, 0x62, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x20, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44,
	0x65, 0x62, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1a, 0x22, 0x12, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2f, 0x64, 0x6f, 0x77, 0x6e, 0x3a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x4a, 0x5a, 0x48,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x6c,
	0x65, 0x73, 0x6f, 0x6e, 0x75, 0x6e, 0x7a, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x72, 0x65,
	0x64, 0x69, 0x73, 0x2d, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transaction_service_pb_Transactions_proto_rawDescOnce sync.Once
	file_transaction_service_pb_Transactions_proto_rawDescData = file_transaction_service_pb_Transactions_proto_rawDesc
)

func file_transaction_service_pb_Transactions_proto_rawDescGZIP() []byte {
	file_transaction_service_pb_Transactions_proto_rawDescOnce.Do(func() {
		file_transaction_service_pb_Transactions_proto_rawDescData = protoimpl.X.CompressGZIP(file_transaction_service_pb_Transactions_proto_rawDescData)
	})
	return file_transaction_service_pb_Transactions_proto_rawDescData
}

var file_transaction_service_pb_Transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transaction_service_pb_Transactions_proto_goTypes = []interface{}{
	(*CreditAccountRequestBody)(nil), // 0: transaction.CreditAccountRequestBody
	(*CreditAccountRequest)(nil),     // 1: transaction.CreditAccountRequest
	(*DebitAccountRequestBody)(nil),  // 2: transaction.DebitAccountRequestBody
	(*DebitAccountRequest)(nil),      // 3: transaction.DebitAccountRequest
	(*emptypb.Empty)(nil),            // 4: google.protobuf.Empty
}
var file_transaction_service_pb_Transactions_proto_depIdxs = []int32{
	0, // 0: transaction.CreditAccountRequest.body:type_name -> transaction.CreditAccountRequestBody
	2, // 1: transaction.DebitAccountRequest.body:type_name -> transaction.DebitAccountRequestBody
	1, // 2: transaction.TransactionServiceRPC.CreditAccount:input_type -> transaction.CreditAccountRequest
	3, // 3: transaction.TransactionServiceRPC.DebitAccount:input_type -> transaction.DebitAccountRequest
	4, // 4: transaction.TransactionServiceRPC.CreditAccount:output_type -> google.protobuf.Empty
	4, // 5: transaction.TransactionServiceRPC.DebitAccount:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transaction_service_pb_Transactions_proto_init() }
func file_transaction_service_pb_Transactions_proto_init() {
	if File_transaction_service_pb_Transactions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transaction_service_pb_Transactions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditAccountRequestBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_pb_Transactions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_pb_Transactions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebitAccountRequestBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_pb_Transactions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebitAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transaction_service_pb_Transactions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_service_pb_Transactions_proto_goTypes,
		DependencyIndexes: file_transaction_service_pb_Transactions_proto_depIdxs,
		MessageInfos:      file_transaction_service_pb_Transactions_proto_msgTypes,
	}.Build()
	File_transaction_service_pb_Transactions_proto = out.File
	file_transaction_service_pb_Transactions_proto_rawDesc = nil
	file_transaction_service_pb_Transactions_proto_goTypes = nil
	file_transaction_service_pb_Transactions_proto_depIdxs = nil
}
